/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI */

#ifndef _Included_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
#define _Included_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPlay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPlay
  (JNIEnv *, jobject);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPlay2
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPlay2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPrepareAsync
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPrepareAsync
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPrepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPrepare
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
