/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI */

#ifndef _Included_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
#define _Included_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPrepareAsync
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPrepareAsync
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPrepare
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPrepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nStart
  (JNIEnv *, jobject);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nPause
  (JNIEnv *, jobject);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nResume
  (JNIEnv *, jobject);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nStop
  (JNIEnv *, jobject);

/*
 * Class:     com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI
 * Method:    nSeekTo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_liuy_myffmpegplayer_ffmpegplayer_MediaPlayerJNI_nSeekTo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
