//
// Created by freed on 2020/1/25.
//

#ifndef MYFFMPEGPLAYER_MYCONSTS_H
#define MYFFMPEGPLAYER_MYCONSTS_H

#include "android_log.h"
#define TAG "MY_FFMPEG_TAG"
//#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)
//#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)

#define AUDIO_SAMPLE_RATE 44100

//播放错误码
#define FIND_STREAM_ERROR_CODE -0x10
#define FIND_AUDIO_STREAM_ERROR_CODE -0x011
#define FIND_AUDIO_DECODER_ERROR_CODE -0x012
#define FIND_VIDEO_STREAM_ERROR_CODE -0x013
#define SWS_GET_CONTEXT_ERROR_CODE -0x014
#define CODEC_FIND_DECODER_ERROR_CODE -0x11
#define CODEC_ALLOC_CONTEXT_ERROR_CODE -0x12
#define SWR_ALLOC_SET_OPTS_ERROR_CODE -0x15
#define SWR_CONTEXT_INIT_ERROR_CODE -0x16
#define SWR_CONTEXT_IN
#define INIT_RTMP_CONNECT_ERROR_CODE -0x20
#define INIT_RTMP_CONNECT_STREAM_ERROR_CODE -0x21
//播放错误码结束
#endif //MYFFMPEGPLAYER_MYCONSTS_H
